/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MatchResults } from "@stencil/router";
import { Product } from "./components/stofrunt-product-list/stofrunt-product-list";
export namespace Components {
    interface AppHome {
    }
    interface AppProfile {
        "match": MatchResults;
    }
    interface AppRoot {
    }
    interface ProductPage {
        "match": MatchResults;
    }
    interface ProductsPage {
    }
    interface StofruntCartItem {
        "cartItem": any;
    }
    interface StofruntProductItem {
        "product": Product;
    }
    interface StofruntProductList {
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLProductPageElement extends Components.ProductPage, HTMLStencilElement {
    }
    var HTMLProductPageElement: {
        prototype: HTMLProductPageElement;
        new (): HTMLProductPageElement;
    };
    interface HTMLProductsPageElement extends Components.ProductsPage, HTMLStencilElement {
    }
    var HTMLProductsPageElement: {
        prototype: HTMLProductsPageElement;
        new (): HTMLProductsPageElement;
    };
    interface HTMLStofruntCartItemElement extends Components.StofruntCartItem, HTMLStencilElement {
    }
    var HTMLStofruntCartItemElement: {
        prototype: HTMLStofruntCartItemElement;
        new (): HTMLStofruntCartItemElement;
    };
    interface HTMLStofruntProductItemElement extends Components.StofruntProductItem, HTMLStencilElement {
    }
    var HTMLStofruntProductItemElement: {
        prototype: HTMLStofruntProductItemElement;
        new (): HTMLStofruntProductItemElement;
    };
    interface HTMLStofruntProductListElement extends Components.StofruntProductList, HTMLStencilElement {
    }
    var HTMLStofruntProductListElement: {
        prototype: HTMLStofruntProductListElement;
        new (): HTMLStofruntProductListElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
        "product-page": HTMLProductPageElement;
        "products-page": HTMLProductsPageElement;
        "stofrunt-cart-item": HTMLStofruntCartItemElement;
        "stofrunt-product-item": HTMLStofruntProductItemElement;
        "stofrunt-product-list": HTMLStofruntProductListElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface AppProfile {
        "match"?: MatchResults;
    }
    interface AppRoot {
    }
    interface ProductPage {
        "match"?: MatchResults;
    }
    interface ProductsPage {
    }
    interface StofruntCartItem {
        "cartItem"?: any;
    }
    interface StofruntProductItem {
        "onAddProductToCart"?: (event: CustomEvent<Product>) => void;
        "product"?: Product;
    }
    interface StofruntProductList {
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-profile": AppProfile;
        "app-root": AppRoot;
        "product-page": ProductPage;
        "products-page": ProductsPage;
        "stofrunt-cart-item": StofruntCartItem;
        "stofrunt-product-item": StofruntProductItem;
        "stofrunt-product-list": StofruntProductList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "product-page": LocalJSX.ProductPage & JSXBase.HTMLAttributes<HTMLProductPageElement>;
            "products-page": LocalJSX.ProductsPage & JSXBase.HTMLAttributes<HTMLProductsPageElement>;
            "stofrunt-cart-item": LocalJSX.StofruntCartItem & JSXBase.HTMLAttributes<HTMLStofruntCartItemElement>;
            "stofrunt-product-item": LocalJSX.StofruntProductItem & JSXBase.HTMLAttributes<HTMLStofruntProductItemElement>;
            "stofrunt-product-list": LocalJSX.StofruntProductList & JSXBase.HTMLAttributes<HTMLStofruntProductListElement>;
        }
    }
}
