/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MatchResults } from "@stencil/router";
import { Product } from "./components/stofrunt-product-list/stofrunt-product-list";
import { Product as Product1 } from "./components/stofrunt-product-list/stofrunt-product-list";
export namespace Components {
    interface AppHome {
    }
    interface AppProfile {
        "match": MatchResults;
    }
    interface AppRoot {
    }
    interface StofruntProductItem {
        "product": Product;
    }
    interface StofruntProductList {
        "products": Product[];
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLStofruntProductItemElement extends Components.StofruntProductItem, HTMLStencilElement {
    }
    var HTMLStofruntProductItemElement: {
        prototype: HTMLStofruntProductItemElement;
        new (): HTMLStofruntProductItemElement;
    };
    interface HTMLStofruntProductListElement extends Components.StofruntProductList, HTMLStencilElement {
    }
    var HTMLStofruntProductListElement: {
        prototype: HTMLStofruntProductListElement;
        new (): HTMLStofruntProductListElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
        "stofrunt-product-item": HTMLStofruntProductItemElement;
        "stofrunt-product-list": HTMLStofruntProductListElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface AppProfile {
        "match"?: MatchResults;
    }
    interface AppRoot {
    }
    interface StofruntProductItem {
        "onAddProductToCart"?: (event: CustomEvent<Product>) => void;
        "product"?: Product;
    }
    interface StofruntProductList {
        "products"?: Product[];
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-profile": AppProfile;
        "app-root": AppRoot;
        "stofrunt-product-item": StofruntProductItem;
        "stofrunt-product-list": StofruntProductList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "stofrunt-product-item": LocalJSX.StofruntProductItem & JSXBase.HTMLAttributes<HTMLStofruntProductItemElement>;
            "stofrunt-product-list": LocalJSX.StofruntProductList & JSXBase.HTMLAttributes<HTMLStofruntProductListElement>;
        }
    }
}
